package Vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author 51934
 */
public class VentanaPago extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTrabajador
     */
    public VentanaPago(){
        initComponents();
        setSize(1250, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaPago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentanaPago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaPago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMetodoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasPendientes = new javax.swing.JTable();
        btnBuscarCitaXDNI = new javax.swing.JButton();
        btnRefrescarTablaCitas = new javax.swing.JButton();
        cajaDNI = new javax.swing.JTextField();
        btnEliminarCita = new javax.swing.JButton();
        btnPagarCita = new javax.swing.JButton();
        radioBtnPagaconTarjeta = new javax.swing.JRadioButton();
        radioBtnPagoEfectivo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        cajaNumeroTarjeta = new javax.swing.JTextField();
        etiquetaimgQRyape = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaFechaVenc = new javax.swing.JTextField();
        cajaCvv = new javax.swing.JTextField();
        imgCard = new javax.swing.JLabel();
        btnCancelarPago = new javax.swing.JButton();
        btnConfirmarPago = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnIraPaciente = new javax.swing.JButton();
        btnIraPago = new javax.swing.JButton();

        buttonGroupMetodoPago.add(radioBtnPagaconTarjeta);
        buttonGroupMetodoPago.add(radioBtnPagoEfectivo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PAGO DE CITAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de Pago: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingresar DNI : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        tablaCitasPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°Cita", "Fecha", "Turno", "Doctor"
            }
        ));
        jScrollPane1.setViewportView(tablaCitasPendientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 520, 180));

        btnBuscarCitaXDNI.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnBuscarCitaXDNI.setText("Buscar");
        jPanel1.add(btnBuscarCitaXDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        btnRefrescarTablaCitas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnRefrescarTablaCitas.setText("Refrescar");
        btnRefrescarTablaCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarTablaCitasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefrescarTablaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 30));
        jPanel1.add(cajaDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, -1));

        btnEliminarCita.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarCita.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnEliminarCita.setText("Eliminar Cita");
        jPanel1.add(btnEliminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 130, 40));

        btnPagarCita.setBackground(new java.awt.Color(51, 51, 255));
        btnPagarCita.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnPagarCita.setText("PAGAR");
        jPanel1.add(btnPagarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 130, 40));

        radioBtnPagaconTarjeta.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        radioBtnPagaconTarjeta.setText("Pago con Tarjeta");
        jPanel1.add(radioBtnPagaconTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        radioBtnPagoEfectivo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        radioBtnPagoEfectivo.setText("Pago Efectivo / Billetera Digital");
        jPanel1.add(radioBtnPagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 63, -1, 450));

        cajaNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumeroTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(cajaNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 320, 30));

        etiquetaimgQRyape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qrYape.png"))); // NOI18N
        jPanel1.add(etiquetaimgQRyape, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 190, 190));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Precio de Cita : S/.10.00");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));
        jPanel1.add(cajaFechaVenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 70, 30));
        jPanel1.add(cajaCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 80, 30));

        imgCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credcard.png"))); // NOI18N
        jPanel1.add(imgCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 380, 240));

        btnCancelarPago.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarPago.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCancelarPago.setText("Cancelar");
        jPanel1.add(btnCancelarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 130, 40));

        btnConfirmarPago.setBackground(new java.awt.Color(0, 255, 0));
        btnConfirmarPago.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnConfirmarPago.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarPago.setText("Confirmar PAGO");
        jPanel1.add(btnConfirmarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 150, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jToolBar1.setBackground(new java.awt.Color(0, 102, 102));
        jToolBar1.setRollover(true);

        btnIraPaciente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnIraPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente.png"))); // NOI18N
        btnIraPaciente.setText("Paciente");
        btnIraPaciente.setAlignmentX(0.5F);
        btnIraPaciente.setFocusable(false);
        btnIraPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIraPaciente.setMargin(new java.awt.Insets(3, 25, 3, 25));
        btnIraPaciente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIraPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraPacienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIraPaciente);

        btnIraPago.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnIraPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay.png"))); // NOI18N
        btnIraPago.setText("Pago");
        btnIraPago.setAlignmentX(0.5F);
        btnIraPago.setFocusable(false);
        btnIraPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIraPago.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnIraPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnIraPago);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIraPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIraPacienteActionPerformed

    private void btnRefrescarTablaCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarTablaCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarTablaCitasActionPerformed

    private void cajaNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNumeroTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCitaXDNI;
    public javax.swing.JButton btnCancelarPago;
    public javax.swing.JButton btnConfirmarPago;
    public javax.swing.JButton btnEliminarCita;
    public javax.swing.JButton btnIraPaciente;
    public javax.swing.JButton btnIraPago;
    public javax.swing.JButton btnPagarCita;
    public javax.swing.JButton btnRefrescarTablaCitas;
    public javax.swing.ButtonGroup buttonGroupMetodoPago;
    public javax.swing.JTextField cajaCvv;
    public javax.swing.JTextField cajaDNI;
    public javax.swing.JTextField cajaFechaVenc;
    public javax.swing.JTextField cajaNumeroTarjeta;
    public javax.swing.JLabel etiquetaimgQRyape;
    public javax.swing.JLabel imgCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JRadioButton radioBtnPagaconTarjeta;
    public javax.swing.JRadioButton radioBtnPagoEfectivo;
    public javax.swing.JTable tablaCitasPendientes;
    // End of variables declaration//GEN-END:variables
}
